/**
 * Noms arabes des villes marocaines (donnée de repli).
 *
 * La source de vérité est la colonne `cities.name_ar` en base : dès qu’une ville
 * y possède un nom arabe, il est utilisé en priorité. Ce fichier ne sert qu’au
 * repli hors ligne et au premier rendu, il ne décide jamais de l’indexation.
 * Aucune ville n’est « prioritaire » ici : la priorité SEO vient des données réelles.
 */
export const CITY_NAME_AR: Record<string, string> = {
  "agadir": "أكادير",
  "agdz": "أكدز",
  "ahfir": "أحفير",
  "ain-aouda": "عين عودة",
  "ain-bni-mathar": "عين بني مطهر",
  "ain-harrouda": "عين حرودة",
  "ain-taoujdate": "عين تاوجدات",
  "ait-baha": "آيت باها",
  "ait-melloul": "أيت ملول",
  "ait-ourir": "أيت أورير",
  "akka": "أقا",
  "aknoul": "أكنول",
  "al-hoceima": "الحسيمة",
  "amizmiz": "أمزميز",
  "aourir": "أورير",
  "assa": "آسا",
  "assilah": "أصيلة",
  "azemmour": "أزمور",
  "azilal": "أزيلال",
  "azrou": "أزرو",
  "ben-ahmed": "بن أحمد",
  "ben-guerir": "بنجرير",
  "beni-mellal": "بني ملال",
  "berkane": "بركان",
  "berrechid": "برشيد",
  "biougra": "بيوكرة",
  "bir-jdid": "بير الجديد",
  "bni-bouayach": "بني بوعياش",
  "bouarfa": "بوعرفة",
  "bouizakarne": "بويزكارن",
  "boujdour": "بوجدور",
  "bouknadel": "بوقنادل",
  "boulemane": "بولمان",
  "boumalne-dades": "بومالن دادس",
  "boumia": "بومية",
  "bouskoura": "بوسكورة",
  "bouznika": "بوزنيقة",
  "casablanca": "الدار البيضاء",
  "chefchaouen": "شفشاون",
  "chichaoua": "شيشاوة",
  "dakhla": "الداخلة",
  "dar-bouazza": "دار بوعزة",
  "demnate": "دمنات",
  "deroua": "الدروة",
  "driouch": "الدريوش",
  "el-borouj": "البروج",
  "el-hajeb": "الحاجب",
  "el-jadida": "الجديدة",
  "el-kelaa-des-sraghna": "قلعة السراغنة",
  "erfoud": "أرفود",
  "errachidia": "الرشيدية",
  "es-semara": "السمارة",
  "essaouira": "الصويرة",
  "figuig": "فكيك",
  "fnideq": "الفنيدق",
  "foum-zguid": "فم زكيد",
  "fquih-ben-salah": "الفقيه بن صالح",
  "fes": "فاس",
  "goulmima": "كلميمة",
  "guelmim": "كلميم",
  "guercif": "جرسيف",
  "had-soualem": "حد السوالم",
  "ifrane": "إفران",
  "imilchil": "إميلشيل",
  "imzouren": "إمزورن",
  "inezgane": "إنزكان",
  "jebha": "الجبهة",
  "jerada": "جرادة",
  "kalaat-mgouna": "قلعة مكونة",
  "karia-ba-mohamed": "قرية بامحمد",
  "kasba-tadla": "قصبة تادلة",
  "kenitra": "القنيطرة",
  "ketama": "كتامة",
  "khemisset": "الخميسات",
  "khenifra": "خنيفرة",
  "khouribga": "خريبكة",
  "ksar-el-kebir": "القصر الكبير",
  "laayoune": "العيون",
  "larache": "العرائش",
  "marrakech": "مراكش",
  "martil": "مارتيل",
  "mdiq": "المضيق",
  "mechra-bel-ksiri": "مشرع بلقصيري",
  "meknes": "مكناس",
  "midar": "ميضار",
  "midelt": "ميدلت",
  "mirleft": "ميرلفت",
  "missour": "ميسور",
  "mohammedia": "المحمدية",
  "moulay-bousselham": "مولاي بوسلهام",
  "moulay-idriss-zerhoun": "مولاي إدريس زرهون",
  "mediouna": "مديونة",
  "nador": "الناظور",
  "nouaceur": "النواصر",
  "oualidia": "الوليدية",
  "ouarzazate": "ورزازات",
  "ouazzane": "وزان",
  "oued-laou": "واد لاو",
  "oued-zem": "وادي زم",
  "oujda": "وجدة",
  "oulad-berhil": "أولاد برحيل",
  "ouled-abbou": "أولاد عبو",
  "ouled-teima": "أولاد تايمة",
  "oulmes": "أولماس",
  "outat-el-haj": "أوطاط الحاج",
  "rabat": "الرباط",
  "ras-el-ma": "رأس الماء",
  "rissani": "الريصاني",
  "rommani": "الرماني",
  "safi": "آسفي",
  "sale": "سلا",
  "saidia": "السعيدية",
  "sefrou": "صفرو",
  "selouane": "سلوان",
  "settat": "سطات",
  "sidi-allal-el-bahraoui": "سيدي علال البحراوي",
  "sidi-bennour": "سيدي بنور",
  "sidi-ifni": "سيدي إفني",
  "sidi-kacem": "سيدي قاسم",
  "sidi-moussa": "سيدي موسى",
  "sidi-rahal": "سيدي رحال",
  "sidi-slimane": "سيدي سليمان",
  "sidi-smail": "سيدي إسماعيل",
  "sidi-yahya-el-gharb": "سيدي يحيى الغرب",
  "skhirate": "الصخيرات",
  "skoura": "سكورة",
  "souk-sebt-ould-nemma": "سوق السبت أولاد النمة",
  "tafraout": "تافراوت",
  "tahannaout": "تحناوت",
  "tahla": "تاهلة",
  "tamesna": "تامسنا",
  "tan-tan": "طانطان",
  "tanger": "طنجة",
  "taounate": "تاونات",
  "taourirt": "تاوريرت",
  "tarfaya": "طرفاية",
  "targuist": "تارجيست",
  "tarhjijt": "تغجيجت",
  "taroudant": "تارودانت",
  "tata": "طاطا",
  "taza": "تازة",
  "tendrara": "تندرارة",
  "tiflet": "تيفلت",
  "tinghir": "تنغير",
  "tinjdad": "تنجداد",
  "tissa": "تيسة",
  "tit-mellil": "تيط مليل",
  "tiznit": "تزنيت",
  "temara": "تمارة",
  "tetouan": "تطوان",
  "youssoufia": "اليوسفية",
  "zagora": "زاكورة",
  "zaida": "زايدة",
  "zaio": "زايو",
  "zemamra": "الزمامرة",
  "zoumi": "زومي",
};
